RaiMan/SikuliX1

- API/src/main/java/org/sikuli/natives/WinUtil.java
- API/src/main/java/org/sikuli/script/App.java
We had problems focusing windows with Unicode characters in titles (like #53 ).
Furthermore the focus function using the window title never really worked for us.
This implementation get rid of the tasklist calls and replaces them with JNA logic. Some other methods of the native WinUtils  library (where is the C++ code  for this stuff?) are also reimplemented using JNA.
It also tries to better find apps based on the window title.
And it removes the open call in the App.focus() method (this gives a nasty popup when we don't find an app with the given title).
> WinUtil unicode

- API/src/main/java/org/sikuli/basics/Settings.java
- API/src/main/java/org/sikuli/natives/SXUser32.java
- API/src/main/java/org/sikuli/script/Key.java
- API/src/main/java/org/sikuli/script/KeyboardLayout.java
- API/src/main/java/org/sikuli/script/RobotDesktop.java
The SikuliX type function only reliably works with the US keyboard layout .
This due to the fact that the key code combinations are hard coded in the Key class. And even if the key combinations wouldn't be hard coded, AWT Robot can't handle key codes for unicode characters (e.g. öäü on German keyboards) at all.
The new implementation bypasses AWT Robot entirely for key presses and key releases on Windows (other OSes still use AWT Robot with the default behaviour and the hard coded US layout). 
It automatically builds a key mapping based on the currently selected locale (similar to the native implementation in https://github.com/frohoff/jdk8u-jdk/blob/master/src/windows/native/sun/windows/awt_Component.cpp, but with full Unicode support). Then it uses this mapping to get the key code for a …
> Detect current keyboard layout and use it for type (on Windows)

- API/src/main/java/org/sikuli/script/KeyboardLayout.java
- API/src/main/java/org/sikuli/script/RobotDesktop.java
Use proper Windows VK codes when building Windows layout (no more mixup with AWT codes).
Keys like WIN and CONTEXT should work now. ALTGR can now be used as a modifier.
> Better separation of AWT and Windows keys

- API/src/main/java/org/sikuli/script/ScreenImage.java
Relatively fast method to test if two ScreenImages are exactly the same. Can sometimes be convenient in scripts to just compare for example two screenshots like scr1.equals(scr2).
> Override equals for ScreenImage to perform a pixel comparison

- IDE/src/main/java/org/sikuli/ide/SikuliIDE.java
- IDE/src/main/java/org/sikuli/scriptrunner/ScriptingSupport.java
Under some circumstances, the new ansync script runner initialization breaks scripts running with the -r option. This due to the fact that in such a case ScriptingSupport.init() gets called and returns immediately (this is lesser an issue inside the IDE because we don't run scripts immediately after the init call).
Adding an async parameter which can be set to true when initalizing from SikulixIDE or false otherwise mitigate that issue (although I'm not sure if this is really the final solution).
Furthermore the implementation with the runningInit flag and the while loop was not thread safe. The synchronized block has the same effect, is thread safe and overall more elegant :-)
> Fix async script runner init with -r option

- API/src/main/java/org/sikuli/script/ScreenImage.java
Some performance comparisons showed that the nested for loop for image comparison is quite slow. Use much faster findChanges (which use OpenCV) instead.
ScreenImage.equals: 14.78
Finder.find: 345.47
Finder.findChanges: 15.77
> Use findChanges instead of nested for loop in ScreenImage equals

- IDE/src/main/java/org/sikuli/ide/EditorConsolePane.java
- IDE/src/main/java/org/sikuli/scriptrunner/JRubyScriptRunner.java
- IDE/src/main/java/org/sikuli/scriptrunner/JSScriptRunner.java
- IDE/src/main/java/org/sikuli/scriptrunner/JythonScriptRunner.java
- IDE/src/main/java/org/sikuli/scriptrunner/RemoteRunner.java
- IDE/src/main/java/org/sikuli/scriptrunner/ScriptingSupport.java
Implementing this lazy loading stuff was simpler than expected. Almost everything is already there.
Now, if ScriptingSupport.init is done synchronously (e.g. IDE with -r) the runners are not initialized immediately anymore. Instead, initialization is started inside the getRunner() before the runner starts for the first time.
In case of the asynchronous init (IDE without -r), all runners are still initialized immediately.
Now we have the best of  both worlds. Fast IDE startup and fast script runs using the -r option.
See issue #94
> Lazily load runners in case of synchronous ScriptingSupport init

- IDE/src/main/java/org/sikuli/ide/EditorLineNumberView.java
Line number popup was not working on Windows.
The Javadoc of MouseEvent.isPopupTrigger() gives the explanation:
> isPopupTrigger
> public boolean isPopupTrigger()
> Returns whether or not this mouse event is the popup menu trigger event for the platform.
> Note: Popup menus are triggered differently on different systems. Therefore, isPopupTrigger should be checked in both mousePressed and mouseReleased for proper cross-platform functionality.
> Make line number context menu working on windows

- API/src/main/java/org/sikuli/script/runners/SikulixRunner.java
I found a small bug and fixed it. I'm glad if it help you.
- org.sikuli.script.runners.SikulixRunner : call Runner#run() without script args
> fixed: SikulixRunner: run with script args

- API/src/main/java/org/sikuli/natives/WinUtil.java
Hello RaiMan,
I found a small bug and fixed it.
- org.sikuli.natives.WinUtil : getWindow(App app, int winNum) not return null when App isn't running
**Detail**
I read and tried https://sikulix-2014.readthedocs.io/en/latest/appclass.html#window .
```
myApp = App("Firefox")
if not myApp.window(): # no window(0) - Firefox not open
App.open("c:\\Program Files\\Mozilla Firefox\\Firefox.exe")
wait(2)
myApp.focus()
wait(1)
type("l", KEY_CTRL) # switch to address field
```
I expected myApp.window() return None when Firefox not open.
But, myApp.window() return Region object.
> fixed: WinUtil: getWindow() return null when App isn't running

- API/src/main/java/org/sikuli/script/support/RunTime.java
The -f option must have been lost somewhere.
This commit brings it back setting the log file of Debug.
> Bring back -f option

- IDE/src/main/java/org/sikuli/ide/EditorPane.java
Ensures that caret position is at least 0 when restoring caret position in EditorPane#restoreCaretPosition(). Otherwise we get an InvalidIndex Exception when saving an empty document. This happens to me quite often when I open a new tab and save it right away.
> Fix save for tab with empty document.

- API/src/main/java/org/sikuli/script/runners/JythonRunner.java
This PR normalized Python code to make it conveniently running with "run to" / "run from".
It normalizes indentations and completes code blocks to get valid code as much as feasible.
E.g.
```
try:
if True:
print("foo")
```
becomes
```
try:
if True:
print("foo")
except:
raise
```
or
```
else:
print("foo")
except:
print("error")
```
becomes
```
try:
if True:
pass
else:
print("foo")
except:
print("error")
```
It also handles some edge cases when placing the runTo or runFrom cursor to silly line numbers.
All stuff  works nested and with spaces or tabs.
Later we could do the same optimizations for JRuby and JavaScript as well.
> Implement code normalization for Jython runLines

- API/src/main/java/org/sikuli/basics/PreferencesUser.java
- API/src/main/java/org/sikuli/script/runners/JythonRunner.java
- IDE/src/main/java/org/sikuli/ide/EditorConsolePane.java
- IDE/src/main/java/org/sikuli/ide/EditorPane.java
This PR implements the suggestions from PR #150 .
Further it clears the console and resets the error line before runLines.
During implementation (of the normalize feature) I noticed that EditorConsolePane does not play nicely with preformatted text. For example it eats up multiple spaces. This due to the fact that it basically uses HTML span elements to present the log messages. I changed the span to pre and the font-family to monospace. Looks much more like a console now :-)
Before:
After:
> Runlines suggestions / Formatting in EditorConsolePane

- API/src/main/java/org/sikuli/script/support/ExtensionManager.java
- API/src/main/java/org/sikuli/script/support/RunTime.java
- IDE/src/main/java/org/sikuli/ide/SikulixIDE.java
Commit 7801e9adf871a80a2711e3d7a56250998808e4f7 broke running with -r because RunTime.start  now really detached the newly created process.
This PR change script / server startup that it is no longer necessary to spawn a separate process for it. Instead it adds the jar files to the class loader using reflection.
> Fixes -r startup not to detach anymore

- IDE/src/main/java/org/sikuli/ide/PatternPaneScreenshot.java
- IDE/src/main/java/org/sikuli/ide/PatternWindow.java
At some screen resolutions (e.g. 16:10) the bottom part of the preview screenshot is always cut off. If one would like to see this part one has to manually resize the PatternWindow that the screenshot gets scaled to a smaller height.
This PR optimizes the PattenWindow size beforehand that the whole screeshot fits into the panel.
Furthermore it centers the window on the screen.
> Optimizes PatternWindow size to the aspect ratio of the screen

- API/src/main/java/org/sikuli/script/runners/ProcessRunner.java
- API/src/main/java/org/sikuli/script/support/ExtensionManager.java
- API/src/main/java/org/sikuli/script/support/RunTime.java
See #169.
Dynamically extending the class path using reflection just does not work out in newer JDKs.
Revert it back to the "new process" solution for now, until we have a working, better solution.
At least in the new version the parent process now waits for termination of its child in case of -r, -s, -p :-)
> Revert failed class path extension experiment to "new process" solution

- API/src/main/java/org/sikuli/script/runners/ZipRunner.java
- IDE/src/main/java/org/sikuli/ide/EditorPane.java
Because of the .class file check in the ZipRunner it is not possible anymore to run .jar files directly using the -r option. ZipRunner simply doesn't return an effective runner in case of the inner script is a $py.class file.
This PR moves this check to the IDE EditorPane.
> Move .class file check to IDE

- API/src/main/java/org/sikuli/script/Region.java
`wait("img.png").hover()` does work.
`wait("img.png").mouseMove()` does NOT work.
As stated in JavaDoc, those two methods should do the same. The problem with `mouseMove()` is that it only operates on the `lastMatch` while `hover()` (and most of the other mouse methods) use the `checkMatch()` method to also use the current location.
This PR uses the `checkMatch()` method from within `mouseMove()` as well and delegates `hover()` calls to `mouseMove()`.
> Make Regions mouseMove behaviour identical to hover

- API/src/main/java/org/sikuli/script/support/RunTime.java
Did a rebase of master after some SikuliX absence due to other prios and got a compile error.
You know what this import is for? Seems not to be needed and the package does not even exist on my machine.
`import static jdk.internal.joptsimple.internal.Reflection.invoke;`
After removing it, everything compiles again and still seems to work.
> Remove strange import

- API/src/main/java/org/sikuli/natives/WinUtil.java
This code was added by commit b43b8bc1afad654e37c8bbe48653b088953035a4.
Feel free to keep it there if there is a reason to enum windows when getting env variables.
> Remove unnecessary enumWindows in getEnv()

- API/src/main/java/org/sikuli/script/support/recorder/RecordedEventsFlow.java
Stops feature lookup if there is no feature increase in any direction. This allows to skip a lot of not needed image recognition.
> Recorder: Minor performance optimization

- API/src/main/java/org/sikuli/script/Finder.java
- API/src/main/java/org/sikuli/script/TextRecognizer.java
Using an unsharp mask to sharpen the image, before and after resizing it, dramatically decreases the error rate.
This even allows to decrease the DPI of the image to increase OCR performance.
Many experiments show, that the combination of a DPI value of 192 and a sigma value of 3 for the first respective 5 for the second `unsharpMask()` gives the best results.
And I moved `setVariable("user_defined_dpi", "" + optimumDPI)` inside the `optimize()` method, so there is no need anymore to call it from the outside.
> Better handling of sub pixel rendering (AKA ClearType)

- API/src/main/java/org/sikuli/script/TextRecognizer.java
While Tesseract 3 can handle light text on dark background quite well, Tesseract 4 utterly needs dark text on light background (https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality#inverting-images).
In addition to the enhancements from PR #200 this PR inverts the image if the background is mainly dark.
> Improve OCR for light text on dark background

- API/src/main/java/org/sikuli/script/runnerSupport/JRubySupport.java
- API/src/main/java/org/sikuli/script/runners/AbstractScriptRunner.java
- API/src/main/java/org/sikuli/script/runners/JRubyRunner.java
- API/src/main/java/org/sikuli/script/runners/JavaScriptRunner.java
- API/src/main/java/org/sikuli/script/runners/JythonRunner.java
- API/src/main/java/org/sikuli/script/support/IScriptRunner.java
The Thread.stop() call in AbstractScriptRunner.doAbort() is deprecated and seems to cause problems with STDIO. Because the stop() call is only needed for the JythonRunner, this PR removes the stop() call and adds a special doAbort() implementation in JythonRunner.
> Better abort implementation for JythonRunner

- API/src/main/java/org/sikuli/script/ScreenImage.java
Previous equality check was done using Finder.findChanges() which applies some thresholding when comparing images. ScreenImage.equals() should only return true if the images are 100 percent equal.
> Make ScreenImage.equals() really check for equality

- API/src/main/java/org/sikuli/script/Screen.java
When initializing screens in headless mode, an exception should always been thrown, not only when running the IDE. Otherwise it leads to NullPointerExceptions later which are hard to trace back to headless mode (see issue #209).
> Always throw exception when trying to initialize screens in headless mode

- API/src/main/java/org/sikuli/script/Screen.java
Solves issues #120 and #184.
The problem was that Mouse.init() tries to move the mouse to the current screen on each iteration, but the target screen has not been initialized yet. This PR defers Mouse.init() until all screens have been initialized.
Reading the relevant source code, I would consider it safe moving Mouse.init() outside the for loop.
> Move Mouse.init() outside the for loop

- API/src/main/java/org/sikuli/script/support/RunTime.java
We occasionally get a ClassNotFoundException on Windows concerning the VNCScreen class. After this we have to teminate SikuliX using the Task Manager.
Don't know exactly why the Exception occurs and can't reproduce it reliably, so I would consider a simple try/catch a good enough fix here.
> Handle the occasionally occurring ClassNotFoundException during cleanUp

- API/src/main/java/org/sikuli/script/SX.java
Solves issue #229.
When a script is saved and has incomplete strings, then an empty popup appears which should contain a message and buttons. This happens because the UI related code is not executed inside the UI dispatcher thread and the UI dispatcher thread itself is blocked inside the while loop right after opening the popup. This also means that all popups created from the SX class are flawed.
This PR corrects the synchronization with the UI dispatcher thread. Opening a popup now works from within the UI dispatcher and other threads. It also properly implements focusing the password field.
> Correctly synchronize UI and other threads when opening a SX popup.

- IDE/src/main/java/org/sikuli/ide/ButtonCapture.java
- IDE/src/main/java/org/sikuli/ide/EditorRegionButton.java
The IDE might appear on the captured screenshot otherwise.
In some places, the delay is already present. Added it in the other places as well.
> Add some delay after setting IDE to invisible to give it some time to vanish

- IDE/src/main/java/org/sikuli/ide/PatternWindow.java
After resizing an image in the pattern window the lines are displaced. This is a minor annoyance because the displacement gets fixed automatically upon the next reparse/repaint (e.g. by simply clicking into the editor area). But because it just looks bad, this PR adds an additional doReparse() when the image has been resized.
> Fix line displacement after resizing image

- API/src/main/java/org/sikuli/util/Highlight.java
Whenever the highlightOn() is used, prevent SikuliX from stealing the app focus.
Also, prevent the JFrame from showing on the taskbar
> Fix steal focus and show on taskbar

- IDE/src/main/java/org/sikuli/ide/PatternPaneTargetOffset.java
- IDE/src/main/java/org/sikuli/ide/PatternWindow.java
- IDE/src/main/java/org/sikuli/idesupport/Resizable.java
Fixes regression added with PR #247.
When the bounds and the click point changes at the same time, the click point change gets lost due to the `doReparse()` call. A repaint() is sufficient as well to mitigate the issue solved in PR #247.
It also fixes a case when the click point is set outside the resize box. Previously this was also interpreted as a resize and triggered the said `doReparse()`.
> Do not reparse editor pane on pattern image resize

- IDE/src/main/java/org/sikuli/ide/EditorPane.java
Problem was that the Pattern takes the similarity as double and in the EditorPane we get the similarity as float. 0.7f is 0.699999988079071d which is obviously not the same. This caused the code generator to produce the longer version.
Doing this somewhat strange conversion gives the proper double value.
To better illustrate the problem:
```
float f = 0.7f;
double d = (double) f; // 0.699999988079071d
String.format(Locale.ENGLISH, "%.2f", d); // "0.70"
d == f; // false
String s = Float.toString(f); // "0.7"
d = Double.parseDouble(s); // 0.7d
d == f; // true
```
I hate computers :-)
> Fix Pattern code generation when adding pattern using the capture button

- API/src/main/java/org/sikuli/basics/Debug.java
> Do not use String.format() in Debug.log() if no args are given

- API/src/main/java/org/sikuli/script/Key.java
- API/src/main/java/org/sikuli/script/Mouse.java
- API/src/main/java/org/sikuli/script/Region.java
- API/src/main/java/org/sikuli/script/support/Recorder.java
- API/src/main/java/org/sikuli/script/support/generators/ICodeGenerator.java
- API/src/main/java/org/sikuli/script/support/generators/JythonCodeGenerator.java
- API/src/main/java/org/sikuli/script/support/recorder/RecordedEventsFlow.java
- API/src/main/java/org/sikuli/script/support/recorder/actions/ClickAction.java
- API/src/main/java/org/sikuli/script/support/recorder/actions/MouseDownAction.java
- API/src/main/java/org/sikuli/script/support/recorder/actions/MouseMoveAction.java
- API/src/main/java/org/sikuli/script/support/recorder/actions/MouseUpAction.java
- API/src/main/java/org/sikuli/script/support/recorder/actions/MouseWheelAction.java
- API/src/main/java/org/sikuli/script/support/recorder/actions/PatternAction.java
- API/src/main/java/org/sikuli/script/support/recorder/actions/WaitAction.java
This PR allows the recording of mouse wheel actions.
Additionally it was needed to straighten the Region class because there were many inconsistencies regarding available method parameters. For example it was not possible at all to use modifiers for wheel actions. And the click methods (click, doubleClick, rightClick) didn't allow to set the Modifiers as String (Key.CTRL + Key.SHIFT instead of KeyModifier.CTRL | KeyModifier.SHIFT).
> Implements recording of mouse wheel

- API/src/main/java/org/sikuli/script/Region.java
This is needed because the `Screen` class overrides the `getScreen()` method to provide itself as screen. In this case the member variable `scr` is never set and accessing `this.scr.something` results in a nasty `NullPointerException`.
Fixes issue #267
> Use getScreen() instead of this.scr in Region

- API/src/main/java/org/sikuli/script/Image.java
- API/src/main/java/org/sikuli/script/TextRecognizer.java
The longer I play around with Tesseract the more I have the impression that resizing based on the current screen resolution is not a good idea at all.
- With LSTM it seems to be VERY important that the height of an upper case letter is between 20 and 30 px (see [here](https://groups.google.com/forum/#!msg/tesseract-ocr/Wdh_JJwnw94/24JHDYQbBQAJ)). This is difficult to achieve with the current solution.
- With the current solution the same script behaves differently on systems with different screen resolutions.
- Setting user_defined_dpi has no effect at all on accuracy, so just setting it to 70 to avoid the error message seems to be good enough
- Using a resize factor makes it is easier to reason about the expected behavior.
This would mitigate issues like #278 and #246. I'm not sure if it …
> Use a configurable resize factor instead of calculating it based on the screen resolution.

- API/src/main/java/org/sikuli/script/support/recorder/RecordedEventsFlow.java
Use LinkedHashSet instead of ArrayList to ensure that each modifier is there only once.
Fixes issue #297
> Recorder: Fix multiple modifiers

- API/src/main/java/org/sikuli/script/Element.java
- API/src/main/java/org/sikuli/script/Pattern.java
Target offset is broken in current master. E.g. click is always performed to the center.
First problem was, that the offset is not passed to the target image of the pattern. When we later get the image (in getLocationFromTarget()), the information is lost. Second problem was that the offset doesn't get passed to the resulting match.
This PR adds the missing functionality.
> Fix target offset

- API/src/main/java/org/sikuli/natives/SXUser32.java
- API/src/main/java/org/sikuli/script/support/RobotDesktop.java
Use `keybd_event` instead of  `SendInput`. Works much better on our side in some use cases. AWT Robot is also doing it exactly this way (https://github.com/frohoff/jdk8u-jdk/blob/da0da73ab82ed714dc5be94acd2f0d00fbdfe2e9/src/windows/native/sun/windows/awt_Robot.cpp#L317).
> Fix lost key events

- API/src/main/java/org/sikuli/script/Element.java
call getStackTrace and logx only if the level >= DEBUG_LEVEL
furthermore we should using logging system (such slf4j-api + log4j2 or logback)
> fix: improve Element.log performance

- API/src/main/java/org/sikuli/script/runners/AbstractLocalFileScriptRunner.java
Sikulix failed with -r option (NullPointerException) because there is no image path before the first script run. Previously I only tested the stuff from the IDE where the image path is always there. Now the existence of the current image path is tested, if not there it is not added to the Deque.
> Fix bundle path handling when run with -r option
