API/src/main/java/org/sikuli/natives/WinUtil.java

Not restoring minimized windows on focus is just cumbersome. Sorry, my fault :-)

Restore minimized windows on focus

---

API/pom.xml
API/src/main/java/com/tulskiy/keymaster/windows/User32.java
API/src/main/java/com/tulskiy/keymaster/windows/WindowsProvider.java
API/src/main/java/com/tulskiy/keymaster/x11/X11Provider.java
API/src/main/java/org/sikuli/natives/SXUser32.java
API/src/main/java/org/sikuli/script/support/KeyboardLayout.java

Update JNA to the newest version to make it easier to import the SikuliX API into other Java projects.

Update JNA to 5.3.1

---

API/src/main/java/org/sikuli/basics/FileManager.java
API/src/main/java/org/sikuli/natives/MacUtil.java

I met some problem when using App.getApps on Mac (sikulixapi 1.1.4).

fix bug I met in MacUtils.getApps

---

IDE/src/main/java/org/sikuli/ide/SikulixIDE.java
IDE/src/main/java/org/sikuli/idesupport/IDETaskbarSupport.java

Make Sikulix icon working on MacOS as well

---

API/src/main/java/org/sikuli/script/runners/AbstractScriptRunner.java
API/src/main/java/org/sikuli/script/runners/InvalidRunner.java
API/src/main/java/org/sikuli/script/runners/SikulixRunner.java
API/src/main/java/org/sikuli/script/support/IScriptRunner.java
API/src/main/java/org/sikuli/script/support/RunTime.java
API/src/main/java/org/sikuli/script/support/Runner.java
IDE/src/main/java/org/sikuli/ide/EditorPane.java

This PR makes the return value of getEffectiveRunner more declarative by using a class EffectiveRunner for it. It also reverts the canHandle of SikulixRunner to its original version. Now canHandle of SikulixRunner checks if the given script is a directory and if it contains a runnable script.

Makes return value of getEffectiveRunner more declarative

---

API/src/main/java/org/sikuli/script/support/RunTime.java
API/src/main/java/org/sikuli/script/support/Runner.java

New try after mess in PR #148.
Allows to set user args with -r again.

Allow to set args and options in Runner.run*

---

API/src/main/java/org/sikuli/script/support/SikulixServer.java
API/src/main/resources/htdocs/ControlBox.css
API/src/main/resources/htdocs/ControlBox.js

In this PR, I revised Handlers to make the next implementation easy.
I also made the following changes:
- Removed: /start, /startp, /exit, /images, /run
- Added: /scripts/:name/run
- Added: /groups/:name/scrips/:name/run

Revise handlers

---

IDE/src/main/java/org/sikuli/ide/EditorPane.java

This PR adds the abort feature to runLines.

Allow abort for runLines

---

API/deploy.xml
API/pom.xml
API/src/main/java/org/sikuli/script/Key.java
API/src/main/java/org/sikuli/script/support/KeyboardLayout.java
API/src/main/java/org/sikuli/script/support/Recorder.java
API/src/main/java/org/sikuli/script/support/RunTime.java
API/src/main/java/org/sikuli/script/support/generators/ICodeGenerator.java
API/src/main/java/org/sikuli/script/support/generators/JythonCodeGenerator.java
API/src/main/java/org/sikuli/script/support/recorder/RecordedEventsFlow.java
API/src/main/java/org/sikuli/script/support/recorder/actions/ClickAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/IRecordedAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/TypeKeyAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/TypeTextAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/WaitClickAction.java
IDE/src/main/java/org/sikuli/ide/EditorPane.java
IDE/src/main/java/org/sikuli/ide/SikulixIDE.java
IDE/src/main/java/org/sikuli/idesupport/IIDESupport.java
IDE/src/main/java/org/sikuli/idesupport/JRubyIDESupport.java
IDE/src/main/java/org/sikuli/idesupport/JythonIDESupport.java
IDE/src/main/resources/i18n/IDE_de.properties
IDE/src/main/resources/i18n/IDE_en_US.properties

This is a very early preview version. It can already record very basic scripts, although a lot of stuff is not working yet.

 First somewhat working preview version of recorder

---

API/src/main/java/org/sikuli/script/Finder.java
API/src/main/java/org/sikuli/script/support/Recorder.java
API/src/main/java/org/sikuli/script/support/generators/ICodeGenerator.java
API/src/main/java/org/sikuli/script/support/generators/JythonCodeGenerator.java
API/src/main/java/org/sikuli/script/support/recorder/RecordedEventsFlow.java
API/src/main/java/org/sikuli/script/support/recorder/actions/WaitClickAction.java
IDE/src/main/java/org/sikuli/ide/EditorPane.java
IDE/src/main/java/org/sikuli/idesupport/JRubyIDESupport.java

- Fix NPE in non Jython Scripts
- detect if wait is needed before click
- Screenshot rate optimizations

Recorder: Some enhancements

---

API/src/main/java/org/sikuli/script/runners/JythonRunner.java
API/src/main/java/org/sikuli/script/support/Runner.java
API/src/main/java/org/sikuli/script/support/SikulixServer.java

This PR adds a task queue implementation.
Sorry for late:-( 
This work was trial and error.

Add task queue implementation

---

API/src/main/java/org/sikuli/script/support/Recorder.java
API/src/main/java/org/sikuli/script/support/generators/ICodeGenerator.java
API/src/main/java/org/sikuli/script/support/generators/JythonCodeGenerator.java
API/src/main/java/org/sikuli/script/support/recorder/RecordedEventsFlow.java
API/src/main/java/org/sikuli/script/support/recorder/actions/ClickAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/DoubleClickAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/DragDropAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/MouseDownAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/MouseMoveAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/MouseUpAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/RightClickAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/WaitAction.java
IDE/src/main/java/org/sikuli/ide/SikulixIDE.java

- Right click
- Double click
- Drag and drop.
- Click modifiers
- Other minor optimizations
It still has some problems with UI animations. Especially when e.g. a click causes an animation and the user proceeds with the workflow too early. Currently it works best to wait after a click until the animation has finished. Generally speaking: Working too fast during recording is not recommended :-)
Still needs quite some tuning, but it's already fine for a preview.

Recorder third iteration

---

API/deploy.xml
API/pom.xml
API/src/main/java/org/sikuli/script/support/SikulixServer.java

This PR changes response type to application/json.
I added maven deps to API/pom.xml and API/deploy.xml. 
The following is added deps:
```
<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-core</artifactId>
<version>2.9.8</version>
</dependency>
<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-databind</artifactId>
<version>2.9.8</version>
</dependency>
<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-annotations</artifactId>
<version>2.9.8</version>
</dependency>
```

Change response type to application/json

---

API/src/main/java/org/sikuli/script/support/Recorder.java
API/src/main/java/org/sikuli/script/support/recorder/RecordedEventsFlow.java
IDE/src/main/java/org/sikuli/ide/SikulixIDE.java
IDE/src/main/resources/i18n/IDE_de.properties
IDE/src/main/resources/i18n/IDE_en_US.properties

As the title says.
Additionally I added the following translations (en/de):
```
btnRecord=Record ({0})
btnRecordLabel=Record
btnRecordStopHint=Press {0} to stop
processingWorkflow=Processing workflow
```
Who adds the other translations?

Recorder: more robust click detection and ProgressMonitor on stop

---

API/src/main/java/org/sikuli/script/support/Recorder.java
API/src/main/java/org/sikuli/script/support/recorder/RecordedEventsFlow.java

- Allow cancel of workflow processing
- Only handle mouse moves > 10 px (anti tremor)
- Better UI animation handling

More recorder optimizations

---

API/src/main/java/org/sikuli/script/support/Recorder.java
API/src/main/java/org/sikuli/script/support/generators/ICodeGenerator.java
API/src/main/java/org/sikuli/script/support/generators/JythonCodeGenerator.java
API/src/main/java/org/sikuli/script/support/recorder/RecordedEventsFlow.java
API/src/main/java/org/sikuli/script/support/recorder/actions/ClickAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/DoubleClickAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/DragDropAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/IRecordedAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/MouseDownAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/MouseMoveAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/MouseUpAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/RightClickAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/TypeKeyAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/TypeTextAction.java
API/src/main/java/org/sikuli/script/support/recorder/actions/WaitAction.java

Some more optimizations and code cleanup.
Recorder is now productively used by our test team :-)

Recorder code cleanup

---

API/src/main/java/org/sikuli/script/support/Recorder.java

We had the issue that some special keys (e.g. Alt Gr) were blocked inside the SikuliX IDE on Windows. After quite some digging I pinpointed the cause to JNativeHook. For some reason it blocks those keys while its hook is registered.
The obvious fix would be to just register the hook before the recording and unregister it afterwards. But on Linux, for reasons, the whole JVM stops when the hook is going to be unregistered (that was the reason I registered it in the static block and unregistered it within a shutdown handler).
The best would be to find the bug in JNativeHook and I will do this when I've some spare time. For now, an easy solution is to only unregister the hook on Windows. Re-registering on other OSes doesn't hurt because JNativeHook checks the registered state before it …

Register native hook before recording and unregister it afterwards. But only on Windows.

---

API/src/main/java/org/sikuli/script/SX.java

This fixes the broken auto close feature of commit f09c03b0a32beee02254b4f68bfb06bb48c6744a

Fix automatic close after timeout of SX popup

---

IDE/src/main/java/org/sikuli/ide/EditorConsolePane.java
IDE/src/main/java/org/sikuli/ide/EditorPane.java
IDE/src/main/java/org/sikuli/ide/SikulixIDE.java

There is unsynchronized UI access from various other threads. This can lead to strange behavior which is usually very hard do debug.
This PR should fix most of them.

Fixes dispatcher thread synchronization in various places

---

API/src/main/java/org/sikuli/script/SX.java

Just in case you have not already added it yourself. Just close otherwise.

Explicitly dispose frame in SX popup after OK click

---

API/src/main/java/org/sikuli/basics/FileManager.java
IDE/src/main/java/org/sikuli/ide/EditorPane.java

Add cleanup of unused screenshots again

---

API/src/main/java/org/sikuli/basics/FileManager.java
API/src/main/java/org/sikuli/basics/Settings.java
API/src/main/java/org/sikuli/script/Env.java
API/src/main/java/org/sikuli/script/Options.java
API/src/main/java/org/sikuli/script/Region.java
API/src/main/java/org/sikuli/script/Screen.java
API/src/main/java/org/sikuli/script/Sikulix.java
API/src/main/java/org/sikuli/script/TextRecognizer.java
API/src/main/java/org/sikuli/script/support/RunTime.java
API/src/main/java/org/sikuli/script/support/SikulixAPI.java
API/src/main/java/org/sikuli/script/support/SikulixServer.java
API/src/main/java/org/sikuli/util/OverlayCapturePrompt.java
IDE/src/main/java/org/sikuli/ide/PatternPaneScreenshot.java
IDE/src/main/java/org/sikuli/ide/PatternWindow.java
IDE/src/main/java/org/sikuli/ide/SikuliIDEStatusBar.java
IDE/src/main/java/org/sikuli/ide/Sikulix.java
IDE/src/main/java/org/sikuli/ide/SikulixIDE.java

It's sometimes handy to have the match preview on the current screen.

Allow to switch between saved and current screen in the pattern match preview

---

IDE/src/main/java/org/sikuli/ide/PatternPaneScreenshot.java

Somebody has already complained that there is no visual feedback after the switch buttons have been clicked. And he is completely right. The match rectangles just appear after a short time. This PR activates the already present spinner after such a click.
Furthermore it does some minor code cleanup and uses the SynchronizedSet wrapper instead of synchronizing it manually.

Show spinner when setting new screenshot in preview panel plus some minor cleanup

---

API/pom.xml
API/src/main/java/org/sikuli/script/support/Runner.java
IDE/src/main/java/org/sikuli/ide/ButtonCapture.java

Use reflection8 instead of reflection to get rid of Guava

---

IDE/src/main/java/org/sikuli/ide/EditorPane.java
IDE/src/main/java/org/sikuli/ide/EditorPatternButton.java
IDE/src/main/java/org/sikuli/ide/EditorPatternLabel.java
IDE/src/main/java/org/sikuli/ide/EditorRegionButton.java
IDE/src/main/java/org/sikuli/ide/PatternPaneScreenshot.java
IDE/src/main/java/org/sikuli/ide/PatternSimilaritySlider.java
IDE/src/main/java/org/sikuli/ide/PatternWindow.java

To avoid the float to double conversion issues.

Change type of similarity to double in IDE to be compatible with API

---

API/src/main/java/org/sikuli/script/Region.java

I wanted to cherry-pick the commit from PR #268 into another branch derived from master and got so many conflicts that I decided it might be simpler to just merge it manually. And since the work is now already done, here is a PR for it :-)

Manual merge from region_screen into master

---

API/src/main/java/org/sikuli/script/Finder.java
API/src/main/java/org/sikuli/script/OCR.java
API/src/main/java/org/sikuli/script/TextRecognizer.java

Suggestions for OCR refactoring

---

API/src/main/java/org/sikuli/script/Finder.java
API/src/main/java/org/sikuli/script/Image.java
API/src/main/java/org/sikuli/script/OCR.java
API/src/main/java/org/sikuli/script/Region.java
API/src/main/java/org/sikuli/script/TextRecognizer.java

Revise OCR

---

API/src/main/java/org/sikuli/script/support/RobotDesktop.java

Fix ConcurrentModificationException in RobotDesktop.keyUp()

---

API/src/main/java/org/sikuli/script/support/recorder/RecordedEventsFlow.java

Must have been slipped through somewhere during your refactoring :-)

Fix screenshot saving in recorder

---

API/src/main/java/org/sikuli/natives/LinuxUtil.java

Fix for linux. Resolving rectangle for App.
https://github.com/RaiMan/SikuliX1/issues/403

Fix for linux. Resolving rectangle for App.

---

README.md

Update README.md [Corrected typo]
